version: "3.4"
services:
  frontend:
    container_name: frontend
    build:
      context: frontend
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - 3000:3000
    stdin_open: true
    depends_on:
      - backend
    volumes:
      - ./frontend:/usr/src/app
    networks:
      - react-express
      - hadolint
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - mongo
      - hadolint
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - express-mongo
      - react-express
      - hadolint
    expose:
      - 3000
  mongo:
    container_name: mongo
    restart: always
    image: mongo:5.0
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - ./backend/db:/data/db
    networks:
      - express-mongo
    expose:
      - 27017

  hadolint:
    container_name: hadolint
    image: hadolint/hadolint:v1.17.5
    working_dir: /usr/src/app/
    command:
      [
        "hadolint",
        "--config",
        "./backend/hadolint.yaml",
        "./backend/Dockerfile",
      ]
    volumes:
      - ./:/usr/src/app/
    networks:
      - hadolint
    expose:
      - 9000

networks:
  react-express:
  express-mongo:
  hadolint:
